/**
 * Result export — builds a plain-text summary of a result (lab/imaging/other)
 * for sharing via email, messaging, printing, or saving as a note.
 *
 * Kept in its own file to isolate react-native Share imports from the main
 * results service (which is data-layer only).
 */

import { Share } from 'react-native';
import { getEffectiveData } from './results';
import {
  RESULT_TYPE_LABELS,
  RESULT_STATUS_LABELS,
} from '@/lib/types/results';
import type {
  ResultItem,
  ResultLabObservation,
  LabFlag,
} from '@/lib/types/results';
import type { EffectiveImagingData, EffectiveOtherData } from './results';

type ServiceResult<T> =
  | { success: true; data: T }
  | { success: false; error: string };

export interface ResultSummary {
  title: string;
  text: string;
  generatedAt: string;
}

interface GenerateParams {
  result: ResultItem;
  labObservations: ResultLabObservation[];
  profileName: string;
}

const ABNORMAL_FLAGS: LabFlag[] = ['high', 'low', 'abnormal', 'critical'];

function formatLongDate(iso: string): string {
  const d = new Date(iso.length <= 10 ? iso + 'T00:00:00' : iso);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toLocaleDateString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  });
}

function flagMarker(flag: LabFlag | null | undefined): string {
  if (!flag || !ABNORMAL_FLAGS.includes(flag)) return '';
  const label = flag.toUpperCase();
  return ` ** ${label} **`;
}

function formatLabValue(obs: ResultLabObservation): string {
  const name = obs.analyte_name;
  const value = obs.value_text ?? (obs.numeric_value != null ? String(obs.numeric_value) : '—');
  const unit = obs.unit ? ` ${obs.unit}` : '';
  const range =
    obs.ref_range_text ??
    (obs.ref_range_low != null && obs.ref_range_high != null
      ? `${obs.ref_range_low}–${obs.ref_range_high}`
      : null);
  const rangePart = range ? ` (Reference: ${range})` : '';
  return `${name}: ${value}${unit}${rangePart}${flagMarker(obs.flag)}`;
}

function buildStatusLabel(status: ResultItem['status']): string {
  if (status === 'needs_review') return 'Needs Review';
  if (status === 'ready') return 'Ready';
  return RESULT_STATUS_LABELS[status];
}

function buildSummaryText(params: GenerateParams, generatedAt: Date): string {
  const { result, labObservations, profileName } = params;
  const lines: string[] = [];

  const generatedDate = generatedAt.toLocaleDateString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  });

  lines.push('---');
  lines.push('RESULT SUMMARY');
  lines.push(`Generated by CareLead on ${generatedDate}`);
  lines.push('This summary is for informational purposes only. It is not medical advice.');
  lines.push('---');
  lines.push('');

  lines.push(`Patient: ${profileName}`);
  lines.push(`Test: ${result.test_name}`);
  lines.push(`Type: ${RESULT_TYPE_LABELS[result.result_type]}`);
  lines.push(
    `Date Performed: ${result.performed_at ? formatLongDate(result.performed_at) : 'Not recorded'}`,
  );
  lines.push(
    `Date Reported: ${result.reported_at ? formatLongDate(result.reported_at) : 'Not recorded'}`,
  );
  lines.push(`Facility: ${result.facility ?? 'Not recorded'}`);
  lines.push(`Ordering Clinician: ${result.ordering_clinician ?? 'Not recorded'}`);
  lines.push(`Status: ${buildStatusLabel(result.status)}`);
  lines.push('');

  if (result.result_type === 'lab') {
    lines.push('LAB VALUES:');
    if (labObservations.length === 0) {
      lines.push('No lab values recorded.');
    } else {
      for (const obs of labObservations) {
        lines.push(formatLabValue(obs));
      }
    }
    lines.push('');
  } else if (result.result_type === 'imaging') {
    const effective = getEffectiveData(result);
    const imaging =
      effective && 'findings' in effective ? (effective as EffectiveImagingData) : null;

    if (imaging?.modality) {
      lines.push(`Modality: ${imaging.modality}`);
    }
    if (imaging?.body_part) {
      lines.push(`Body Part: ${imaging.body_part}`);
    }
    if (imaging?.modality || imaging?.body_part) {
      lines.push('');
    }

    if (imaging?.findings) {
      lines.push('FINDINGS:');
      lines.push(imaging.findings);
      lines.push('');
    }
    if (imaging?.impression) {
      lines.push('IMPRESSION:');
      lines.push(imaging.impression);
      lines.push('');
    }
    if (imaging?.radiologist) {
      lines.push(`Radiologist: ${imaging.radiologist}`);
      lines.push('');
    }
    if (!imaging || (!imaging.findings && !imaging.impression && !imaging.modality)) {
      lines.push('No imaging details recorded.');
      lines.push('');
    }
  } else {
    const effective = getEffectiveData(result);
    const other =
      effective && 'key_findings' in effective ? (effective as EffectiveOtherData) : null;

    if (other?.test_category) {
      lines.push(`Category: ${other.test_category}`);
      lines.push('');
    }
    if (other?.summary) {
      lines.push('SUMMARY:');
      lines.push(other.summary);
      lines.push('');
    }
    if (other?.key_findings && other.key_findings.length > 0) {
      lines.push('KEY FINDINGS:');
      for (const f of other.key_findings) {
        const label = f.label ?? 'Finding';
        const value = f.value ?? '—';
        lines.push(`- ${label}: ${value}`);
      }
      lines.push('');
    }
    if (
      !other ||
      (!other.summary &&
        !other.test_category &&
        (!other.key_findings || other.key_findings.length === 0))
    ) {
      lines.push('No details recorded.');
      lines.push('');
    }
  }

  if (result.notes && result.notes.trim()) {
    lines.push(`Notes: ${result.notes.trim()}`);
    lines.push('');
  }

  lines.push('---');
  lines.push('This document was generated from patient-managed records in CareLead.');
  lines.push('It has not been verified by a healthcare provider unless otherwise noted.');
  lines.push('For clinical decisions, consult the original report and your healthcare team.');
  lines.push('---');

  return lines.join('\n');
}

/**
 * Build a plain-text summary of a result, including disclaimers. Pure function —
 * does no I/O.
 */
export function generateResultSummary(params: GenerateParams): ResultSummary {
  const generatedAt = new Date();
  const title = `${params.result.test_name} — Result Summary`;
  const text = buildSummaryText(params, generatedAt);
  return { title, text, generatedAt: generatedAt.toISOString() };
}

/**
 * Generate a result summary and open the system Share sheet. Returns the
 * generated summary so callers can also persist it (e.g., append to notes).
 */
export async function generateAndShareSummary(
  params: GenerateParams,
): Promise<ServiceResult<ResultSummary>> {
  const summary = generateResultSummary(params);
  try {
    await Share.share({
      message: summary.text,
      title: summary.title,
    });
    return { success: true, data: summary };
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Share failed';
    return { success: false, error: message };
  }
}
